name: Affirm Metadata Env
description: Read metadata values and place into environment
author: https://github.com/Affirm
requirements:
  - buildkite-agent
configuration:
  properties:
    keys:
      type: array
      minimum: 1