steps:
  - label: ":lint-roller: Lint"
    plugins:
      - docker-compose#v3.3.0:
          run: lint
  - label: ":test_tube: Tests"
    plugins:
      - docker-compose#v3.3.0:
          run: tests
  - label: ":test_tube: Setting meta data"
    commands:
      - 'buildkite-agent meta-data set "hello" "world"'
  - label: ":bomb: Fetching meta-data"
    commands:
      - test $$HELLO = world
    plugins:
      - chronotc/metadata-env#${BUILDKITE_COMMIT}:
          keys:
            - hello=HELLO #remaps node-env key to NODE_ENV <key>=<alias>

